=== felixhpp/ElasticDatax/src/main/resources/elastic/elasticmapping.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--定义根目录节点为elasticMapper, 子节点为property， 可以有多个-->
<!ELEMENT elasticMapper (property+,addProperty*,filters)>
<!--+ ：表示一次或者多次 ? ：表示零次或者一次  * ：表示零次或者多次 无 ：子元素只能出现一次-->
<!ELEMENT property (methodConvertor* | dicConvertor? | dateFormatConvertor? | dateConcatConvertor? | valueFormatConvertor? | sqlConvertor)>
<!ELEMENT methodConvertor (parameter+)>
<!ELEMENT dateFormatConvertor (parameter)>
<!ELEMENT dicConvertor (parameter)>
<!ELEMENT sqlConvertor (#PCDATA)>
<!ELEMENT dateConcatConvertor (dateParameter, timeParameter)>
<!ELEMENT valueFormatConvertor (parameter)>
<!ELEMENT dateParameter (#PCDATA)>
<!ELEMENT timeParameter (#PCDATA)>
<!ELEMENT addProperty (const*,sql*)>
<!ELEMENT parameter (#PCDATA)>
<!ELEMENT const (#PCDATA)>
<!ELEMENT sql (#PCDATA)>
<!ELEMENT filters (sourceFilter, targetFilter)>
<!--对原始对象过滤-->
<!ELEMENT sourceFilter (must,should)>
<!--对转换后的对象过滤-->
<!ELEMENT targetFilter (must,should)>
<!ELEMENT must (filter+)>
<!ELEMENT should (filter+)>
<!ELEMENT filter (#PCDATA)>
<!-- elasticMapper name属性是必须的，且唯一 -->
<!ATTLIST elasticMapper name ID #REQUIRED>
<!-- property sourceName属性是必须的 -->
<!ATTLIST property sourceName CDATA #REQUIRED>
<!-- property targetName属性是必须的 -->
<!ATTLIST property targetName ID #REQUIRED>
<!-- property idField属性是可选的，只能选择true|false -->
<!ATTLIST property idField (true|false) #IMPLED>
<!-- property parentField属性是可选的，只能选择true|false -->
<!ATTLIST property parentField (true|false) #IMPLED>
<!-- property routingField属性是可选的，只能选择true|false -->
<!ATTLIST property routingField (true|false) #IMPLED>
<!--文字描述，可选-->
<!ATTLIST property desc CDATA #IMPLED>
<!-- property valueType属性是可选的，只能选择true|false -->
<!ATTLIST property valueType (
        String | string |
        Integer | int |
        Double | double |
        Float | float |
        Boolean | bool |
        Date | date ) #IMPLED "java.lang.String">
<!ATTLIST property format (
        yyyy-MM-dd |
        yyyy-MM-dd hh:mm:ss |
        hh:mm:ss |
        ) #IMPLED "yyyy-MM-dd">
<!-- methodConvertor 参数方法 -->
<!ATTLIST methodConvertor methodName (
        test |
        )  #REQUIRED>
<!ATTLIST parameter type (
        String | string |
        Integer | int |
        Double | double |
        Float | float |
        Boolean | bool |
        Date | date
        ) #IMPLED "java.lang.String">
<!ATTLIST dicConvertor methodName (
        getByCode
        )  #REQUIRED>
<!ATTLIST dicConvertor dicType (
        DiagnoseType | Deptartment | Sex | National | AdmType | Marital | Hospital |
        DiagnoseName | OrderItem | OrdType | OrdCateage | OrderStatus | Duration |
        Freq | AdmStatus | LisItem | PHDrgMaterial | InstrUsage | PHCGeneric | PHCGoods
        )  #REQUIRED>
<!ATTLIST dateFormatConvertor methodName (
        formatDate |
        ) #REQUIRED "formatDate">
<!--format 日期的类型 shortDate : yyy-mm-dd; longDate: yyyy-mm-dd hh:mm:ss; time: hh:mm:ss-->
<!ATTLIST dateFormatConvertor formatType (
        shortDate | longDate | time |
        ) #REQUIRED "shortDate">
<!ATTLIST dateConcatConvertor methodName (
        concatDatetime |
        ) #REQUIRED "concatDatetime">
<!ATTLIST valueFormatConvertor methodName (
        formatValue |
        ) #REQUIRED "formatValue">
<!ATTLIST dateParameter value CDATA #REQUIRED>
<!ATTLIST timeParameter value CDATA #REQUIRED>
<!ATTLIST const targetName CDATA #REQUIRED>

<!ATTLIST filter filterName CDATA #REQUIRED>
<!ATTLIST filter filterMethod (
        isNotEmpty | equert | notEquert
        ) #REQUIRED>

=== felixhpp/ElasticDatax/src/main/resources/elastic/homepagediagnose.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE elasticMapper SYSTEM "elasticmapping.dtd">
<elasticMapper name="homepagediagnose" desc="病案首页诊断部分">
    <!--doc id 通过病案首页ID + 诊断编码 + 类型-->
    <propertys>
        <property sourceName="documentid" targetName="Hpd_id" desc="ID" idField="true"></property>
        <property sourceName="patientid" targetName="Hpd_AdmNo" desc="就诊ID" parentField="true"></property>
        <property sourceName="visitnumber" targetName="Hpd_RegNo" desc="登记号" routingField="true"></property>
        <property sourceName="DiagName" targetName="Hpd_DiagName" desc="诊断名称"></property>
        <property sourceName="DiagCode" targetName="Hpd_DiagCode" desc="诊断编码"></property>
        <property sourceName="DiagType" targetName="Hpd_DiagType" desc="诊断类型"></property>
        <property sourceName="DiagTypeCode" targetName="Hpd_DiagTypeCode" desc="诊断类型编码"></property>
    </propertys>
</elasticMapper>

=== felixhpp/ElasticDatax/src/main/resources/elastic/orditem.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE elasticMapper SYSTEM "elasticmapping.dtd">
<elasticMapper name="diagnose">
    <!--property配置字段映射信息
        sourceName：源字段名称
        targetName: 目标字段名称
        convert： 是否进行转换， 如果true, 则将通过调用方法或者动态执行sql获取转换后的值
        valueType: 字段数据类型，
        dicType: 字典类型   com.example.demo.core.dics 包下的类路径
        -->
    <property sourceName="ord_id"  targetName="Ord_Id" valueType="String" idField="true"></property>
    <property sourceName="ord_admno" targetName="Ord_AdmNo" valueType="String" parentField="true"></property>
    <property sourceName="ord_regno" targetName="Ord_RegNo" valueType="String" routingField="true"></property>
    <!--医嘱代码-->
    <property sourceName="ord_code" targetName="Ord_DicCode"  valueType="String"></property>
    <!--医嘱名称-->
    <property sourceName="ord_code" targetName="Ord_Name" valueType="String">
        <dicConvertor methodName="getByCode" dicType="OrderItem">
            <parameter></parameter>
        </dicConvertor>
    </property>
    <!--医嘱大分类-->
    <property sourceName="ord_cate_code" targetName="Ord_Category" valueType="String">
        <dicConvertor methodName="getByCode" dicType="OrdCateage">
            <parameter></parameter>
        </dicConvertor>
    </property>
    <!--医嘱类型-->
    <property sourceName="ord_type_code" targetName="Ord_Type" valueType="String">
        <dicConvertor methodName="getByCode" dicType="OrdType">
            <parameter></parameter>
        </dicConvertor>
    </property>
    <!--周期-->
    <property sourceName="ord_period" targetName="Ord_Period" valueType="String">
    </property>
    <!--疗程-->
    <property sourceName="ord_duration_code" targetName="Ord_Duration" valueType="String">
        <dicConvertor methodName="getByCode" dicType="Duration">
            <parameter></parameter>
        </dicConvertor>
    </property>
    <!--用法 - 用药途径-->
    <property sourceName="ord_usage" targetName="Ord_Usage" valueType="String">
    </property>
    <!--频次-->
    <property sourceName="ord_freq_code" targetName="Ord_Freq" valueType="String">
        <dicConvertor methodName="getByCode" dicType="Freq">
            <parameter></parameter>
        </dicConvertor>
    </property>
    <!--医嘱开始时间-->
    <property sourceName="ord_startdate" targetName="Ord_StartTime" valueType="String">
        <dateConcatConvertor methodName="concatDatetime">
            <dateParameter value="ord_startdate"></dateParameter>
            <timeParameter value="ord_starttime"></timeParameter>
        </dateConcatConvertor>
    </property>
    <!--医嘱状态-->
    <property sourceName="ord_status_code" targetName="Ord_Status" valueType="String">
        <dicConvertor methodName="getByCode" dicType="OrderStatus">
            <parameter></parameter>
        </dicConvertor>
    </property>
    <!--医嘱数量-->
    <property sourceName="ord_orderqty" targetName="Ord_OrderQty" valueType="String">
    </property>
    <!--医嘱结束时间-->
    <property sourceName="ord_enddate" targetName="Ord_EndTime" valueType="String">
        <dateConcatConvertor methodName="concatDatetime">
            <dateParameter value="ord_enddate"></dateParameter>
            <timeParameter value="ord_endtime"></timeParameter>
        </dateConcatConvertor>
    </property>
    <!--开医嘱科室-->
    <property sourceName="ord_dept_code" targetName="Ord_Dept" valueType="String">
        <dicConvertor methodName="getByCode" dicType="Deptartment">
            <parameter></parameter>
        </dicConvertor>
    </property>
    <!--执行医嘱科室-->
    <property sourceName="ord_execdept_code" targetName="Ord_ExecDept" valueType="String">
        <dicConvertor methodName="getByCode" dicType="Deptartment">
            <parameter></parameter>
        </dicConvertor>
    </property>
    <!--归一后医嘱编码-->
    <property sourceName="ord_code" targetName="Ord_MedDicCode" valueType="String">
    </property>
    <!--归一后医嘱名称-->
    <property sourceName="ord_code" targetName="Ord_MedDicName" valueType="String">
        <dicConvertor methodName="getByCode" dicType="OrderItem">
            <parameter></parameter>
        </dicConvertor>
    </property>
</elasticMapper>

=== felixhpp/ElasticDatax/src/main/resources/elastic/diagnose.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE elasticMapper SYSTEM "elasticmapping.dtd">
<elasticMapper name="diagnose">
    <!--property配置字段映射信息
        sourceName：源字段名称
        targetName: 目标字段名称
        convert： 是否进行转换， 如果true, 则将通过调用方法或者动态执行sql获取转换后的值
        valueType: 字段数据类型，
        dicType: 字典类型   com.example.demo.core.dics 包下的类路径
        -->
    <property sourceName="diag_id"  targetName="Diag_Id" valueType="String" idField="true"></property>
    <property sourceName="diag_admid" targetName="Diag_AdmId" valueType="String" parentField="true"></property>
    <property sourceName="diag_regno" targetName="Diag_RegNo"  valueType="String" routingField="true"></property>
    <property sourceName="diag_date" targetName="Diag_Time" valueType="String">
       <dateConcatConvertor methodName="concatDatetime">
           <dateParameter value="diag_date"></dateParameter>
           <timeParameter value="diag_time"></timeParameter>
       </dateConcatConvertor>
    </property>
    <property sourceName="diag_type_code" targetName="Diag_Type" valueType="String">
        <dicConvertor methodName="getByCode" dicType="DiagnoseType">
            <parameter></parameter>
        </dicConvertor>
    </property>
    <!--诊断名称  通过编码获取-->
    <property sourceName="diag_name" targetName="Diag_Name" valueType="String">
        <dicConvertor methodName="getByCode" dicType="DiagnoseName">
            <parameter>diag_code</parameter>
        </dicConvertor>
    </property>
    <!--诊断编码-->
    <property sourceName="diag_code" targetName="Diag_Code " valueType="String"></property>
    <!--诊断顺位-->
    <property sourceName="diag_no" targetName="Diag_No" valueType="String"></property>
</elasticMapper>

=== felixhpp/ElasticDatax/src/main/resources/elastic/medicine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE elasticMapper SYSTEM "elasticmapping.dtd">
<elasticMapper name="medicine">
    <!--property配置字段映射信息
        sourceName：源字段名称
        targetName: 目标字段名称
        convert： 是否进行转换， 如果true, 则将通过调用方法或者动态执行sql获取转换后的值
        valueType: 字段数据类型，
        dicType: 字典类型   com.example.demo.core.dics 包下的类路径
        -->
    <!--id字段-->
    <property sourceName="med_id"  targetName="Med_Id" valueType="String" idField="true"></property>
    <!--关联就诊ID-->
    <property sourceName="med_admno" targetName="Med_AdmNo" valueType="String" parentField="true"></property>
    <!--关联登记号-->
    <property sourceName="med_regno" targetName="Med_RegNo" valueType="String" routingField="true"></property>
    <!--用药时段-->
    <property sourceName="med_timeInterval" targetName="Med_TimeInterval" valueType="String"></property>
    <!--用药 - 医嘱名称-->
    <property sourceName="med_ordcode" targetName="Med_OrdName" valueType="String">
        <dicConvertor methodName="getByCode" dicType="OrderItem">
            <parameter></parameter>
        </dicConvertor>
    </property>
    <!--用药商品名称-->
    <property sourceName="med_bisname" targetName="Med_BisName" valueType="String">
        <dicConvertor methodName="getByCode" dicType="OrderItem">
            <parameter></parameter>
        </dicConvertor>
    </property>
    <!--用药通用名称-->
    <property sourceName="ord_cate_code" targetName="Med_GenName" valueType="String">
        <dicConvertor methodName="getByCode" dicType="OrdCateage">
            <parameter></parameter>
        </dicConvertor>
    </property>
    <!--药物名称（用于统计， 不分词）-->
    <property sourceName="ord_type_code" targetName="Med_GenDesc" valueType="String">
        <dicConvertor methodName="getByCode" dicType="OrdType">
            <parameter></parameter>
        </dicConvertor>
    </property>
    <!--药品类别-->
    <property sourceName="ord_period" targetName="Med_Category" valueType="String">
    </property>
    <!--单次剂量-->
    <property sourceName="ord_duration_code" targetName="Med_SingleDose" valueType="String">
        <dicConvertor methodName="getByCode" dicType="Duration">
            <parameter></parameter>
        </dicConvertor>
    </property>
    <!--总剂量-->
    <property sourceName="ord_usage" targetName="Med_TotalDose" valueType="String">
    </property>
    <!--频次-->
    <property sourceName="ord_freq_code" targetName="Ord_Freq" valueType="String">
        <dicConvertor methodName="getByCode" dicType="Freq">
            <parameter></parameter>
        </dicConvertor>
    </property>
    <!--医嘱开始时间-->
    <property sourceName="ord_starttime" targetName="Ord_StartTime" valueType="String">
    </property>
    <!--医嘱状态-->
    <property sourceName="ord_status_code" targetName="Ord_Status" valueType="String">
        <dicConvertor methodName="getByCode" dicType="OrderStatus">
            <parameter></parameter>
        </dicConvertor>
    </property>
    <!--医嘱数量-->
    <property sourceName="ord_orderqty" targetName="Ord_OrderQty" valueType="String">
    </property>
    <!--医嘱结束时间-->
    <property sourceName="ord_endtime" targetName="Ord_EndTime" valueType="String">
    </property>
    <!--开医嘱科室-->
    <property sourceName="ord_dept_code" targetName="Ord_Dept" valueType="String">
        <dicConvertor methodName="getByCode" dicType="Deptartment">
            <parameter></parameter>
        </dicConvertor>
    </property>
    <!--执行医嘱科室-->
    <property sourceName="ord_execdept_code" targetName="Ord_ExecDept" valueType="String">
        <dicConvertor methodName="getByCode" dicType="Deptartment">
            <parameter></parameter>
        </dicConvertor>
    </property>
    <!--归一后医嘱编码-->
    <property sourceName="ord_code" targetName="Ord_MedDicCode" valueType="String">
    </property>
    <!--归一后医嘱名称-->
    <property sourceName="ord_code" targetName="Ord_MedDicName" valueType="String">
        <dicConvertor methodName="getByCode" dicType="OrderItem">
            <parameter></parameter>
        </dicConvertor>
    </property>
</elasticMapper>

=== felixhpp/ElasticDatax/src/main/resources/elastic/operation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE elasticMapper SYSTEM "elasticmapping.dtd">
<elasticMapper name="operation" desc="病案首页手术部分">
    <!--doc id 通过病案首页ID + 手术时间 +  手术编码-->
    <propertys>
        <property sourceName="documentid" targetName="Oper_id" desc="手术ID" idField="true"></property>
        <property sourceName="patientid" targetName="Oper_AdmNo" desc="就诊ID" rowKey="true" parentField="true"></property>
        <property sourceName="visitnumber" targetName="Oper_RegNo" desc="登记号" routingField="true"></property>
        <property sourceName="OperName" targetName="Oper_Name" desc="手术名称"></property>
        <property sourceName="OperDate" targetName="Oper_StartTime" desc="手术开始时间"></property>
        <property sourceName="OperCode" targetName="Oper_GenericCode" desc="手术归一编码"></property>
        <property sourceName="OperName" targetName="Oper_GenericName" desc="手术归一名称"></property>
        <property sourceName="OperLevel" targetName="Oper_Level" desc="手术级别"></property>
        <property sourceName="AnaesWay" targetName="Oper_AnaesWay" desc="麻醉方式"></property>
        <property sourceName="NcisionHealingLevel" targetName="Oper_NcisionHealingLevel" desc="切口愈合等级"></property>
        <property sourceName="Operator" targetName="Oper_Operator" desc="术者"></property>
        <property sourceName="OperaAssistantFir" targetName="Oper_OperaAssistantFir" desc="助1"></property>
        <property sourceName="OperaAssistantSec" targetName="Oper_OperaAssistantSec" desc="助2"></property>
        <property sourceName="AnaesDoc" targetName="Oper_AnaesDoc" desc="麻醉医师"></property>
        <property sourceName="IsCurOpera" targetName="Oper_IsCurOpera" desc="是否本次手术"></property>
    </propertys>
</elasticMapper>
